### ISSUE TITLE
X-Forwarded-* headers are not used for resolving the URI

### ISSUE THREAD

**Issue by kaosko** [weavejester/ring-oauth2#15]
Function redirect-uri should use X-Forwarded-* header values to resolve the URI, at least request.getHeader("X-Forwarded-Proto"). Currently, if your application is behind a reverse proxy that handles https and you resolve a relative redirect link, the generated URI will have http:// instead of https://.

**Comment by weavejester** [comment]
Take a look at the [wrap-forwarded-scheme](https://ring-clojure.github.io/ring-ssl/ring.middleware.ssl.html#var-wrap-forwarded-scheme) function in the [Ring-SSL](https://github.com/ring-clojure/ring-ssl) library. Rather than making every middleware check both the `:scheme` and the `X-Forwarded-Proto` header, it's less code to normalize the request map with middleware.
